version: "3.0"

networks:
  WebApp:
    driver: bridge

services:
  backend:
    container_name: express-backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - /usr/src/expressapp/node_modules
      - ./src:/usr/src/expressapp/src
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: true
      DANGEROUSLY_DISABLE_HOST_CHECK: true
    ports:
      - "${PORT}:${PORT}"
    stdin_open: true
    restart: on-failure
    networks:
      - WebApp